export interface IInstrument {
  family: string;
  instrument: string;
} 

export var Instruments: Array<IInstrument> = [
  { 'family': 'Piano', 'instrument': 'Piano' },
  { 'family': 'Piano', 'instrument': 'Bright Acoustic Piano' },
  { 'family': 'Piano', 'instrument': 'Electric Grand Piano' },
  { 'family': 'Piano', 'instrument': 'Honky-tonk Piano' },
  { 'family': 'Piano', 'instrument': 'Electric Piano 1' },
  { 'family': 'Piano', 'instrument': 'Electric Piano 2' },
  { 'family': 'Piano', 'instrument': 'Harpsichord' },
  { 'family': 'Piano', 'instrument': 'Clavi' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Celesta' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Glockenspiel' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Music Box' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Vibraphone' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Marimba' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Xylophone' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Tubular Bells' },
  { 'family': 'Chromatic Percussion', 'instrument': 'Dulcimer' },
  { 'family': 'Organ', 'instrument': 'Drawbar Organ' },
  { 'family': 'Organ', 'instrument': 'Percussive Organ' },
  { 'family': 'Organ', 'instrument': 'Rock Organ' },
  { 'family': 'Organ', 'instrument': 'Church Organ' },
  { 'family': 'Organ', 'instrument': 'Reed Organ' },
  { 'family': 'Organ', 'instrument': 'Accordion' },
  { 'family': 'Organ', 'instrument': 'Harmonica' },
  { 'family': 'Organ', 'instrument': 'Tango Accordion' },
  { 'family': 'Guitar', 'instrument': 'Acoustic Guitar (nylon)' },
  { 'family': 'Guitar', 'instrument': 'Acoustic Guitar (steel)' },
  { 'family': 'Guitar', 'instrument': 'Electric Guitar (jazz)' },
  { 'family': 'Guitar', 'instrument': 'Electric Guitar (clean)' },
  { 'family': 'Guitar', 'instrument': 'Electric Guitar (muted)' },
  { 'family': 'Guitar', 'instrument': 'Overdriven Guitar' },
  { 'family': 'Guitar', 'instrument': 'Distortion Guitar' },
  { 'family': 'Guitar', 'instrument': 'Guitar harmonics' },
  { 'family': 'Bass', 'instrument': 'Acoustic Bass' },
  { 'family': 'Bass', 'instrument': 'Electric Bass (finger)' },
  { 'family': 'Bass', 'instrument': 'Electric Bass (pick)' },
  { 'family': 'Bass', 'instrument': 'Fretless Bass' },
  { 'family': 'Bass', 'instrument': 'Slap Bass 1' },
  { 'family': 'Bass', 'instrument': 'Slap Bass 2' },
  { 'family': 'Bass', 'instrument': 'Synth Bass 1' },
  { 'family': 'Bass', 'instrument': 'Synth Bass 2' },
  { 'family': 'Strings', 'instrument': 'Violin' },
  { 'family': 'Strings', 'instrument': 'Viola' },
  { 'family': 'Strings', 'instrument': 'Cello' },
  { 'family': 'Strings', 'instrument': 'Contrabass' },
  { 'family': 'Strings', 'instrument': 'Tremolo Strings' },
  { 'family': 'Strings', 'instrument': 'Pizzicato Strings' },
  { 'family': 'Strings', 'instrument': 'Orchestral Harp' },
  { 'family': 'Strings', 'instrument': 'Timpani' },
  { 'family': 'Ensemble', 'instrument': 'String Ensemble 1' },
  { 'family': 'Ensemble', 'instrument': 'String Ensemble 2' },
  { 'family': 'Ensemble', 'instrument': 'SynthStrings 1' },
  { 'family': 'Ensemble', 'instrument': 'SynthStrings 2' },
  { 'family': 'Ensemble', 'instrument': 'Choir Aahs' },
  { 'family': 'Ensemble', 'instrument': 'Voice Oohs' },
  { 'family': 'Ensemble', 'instrument': 'Synth Voice' },
  { 'family': 'Ensemble', 'instrument': 'Orchestra Hit' },
  { 'family': 'Brass', 'instrument': 'Trumpet' },
  { 'family': 'Brass', 'instrument': 'Trombone' },
  { 'family': 'Brass', 'instrument': 'Tuba' },
  { 'family': 'Brass', 'instrument': 'Muted Trumpet' },
  { 'family': 'Brass', 'instrument': 'French Horn' },
  { 'family': 'Brass', 'instrument': 'Brass Section' },
  { 'family': 'Brass', 'instrument': 'SynthBrass 1' },
  { 'family': 'Brass', 'instrument': 'SynthBrass 2' },
  { 'family': 'Reed', 'instrument': 'Soprano Sax' },
  { 'family': 'Reed', 'instrument': 'Alto Sax' },
  { 'family': 'Reed', 'instrument': 'Tenor Sax' },
  { 'family': 'Reed', 'instrument': 'Baritone Sax' },
  { 'family': 'Reed', 'instrument': 'Oboe' },
  { 'family': 'Reed', 'instrument': 'English Horn' },
  { 'family': 'Reed', 'instrument': 'Bassoon' },
  { 'family': 'Reed', 'instrument': 'Clarinet' },
  { 'family': 'Pipe', 'instrument': 'Piccolo' },
  { 'family': 'Pipe', 'instrument': 'Flute' },
  { 'family': 'Pipe', 'instrument': 'Recorder' },
  { 'family': 'Pipe', 'instrument': 'Pan Flute' },
  { 'family': 'Pipe', 'instrument': 'Blown Bottle' },
  { 'family': 'Pipe', 'instrument': 'Shakuhachi' },
  { 'family': 'Pipe', 'instrument': 'Whistle' },
  { 'family': 'Pipe', 'instrument': 'Ocarina' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 1 (square)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 2 (sawtooth)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 3 (calliope)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 4 (chiff)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 5 (charang)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 6 (voice)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 7 (fifths)' },
  { 'family': 'Synth Lead', 'instrument': 'Lead 8 (bass + lead)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 1 (new age)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 2 (warm)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 3 (polysynth)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 4 (choir)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 5 (bowed)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 6 (metallic)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 7 (halo)' },
  { 'family': 'Synth Pad', 'instrument': 'Pad 8 (sweep)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 1 (rain)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 2 (soundtrack)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 3 (crystal)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 4 (atmosphere)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 5 (brightness)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 6 (goblins)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 7 (echoes)' },
  { 'family': 'Synth Effects', 'instrument': 'FX 8 (sci-fi)' },
  { 'family': 'Ethnic', 'instrument': 'Sitar' },
  { 'family': 'Ethnic', 'instrument': 'Banjo' },
  { 'family': 'Ethnic', 'instrument': 'Shamisen' },
  { 'family': 'Ethnic', 'instrument': 'Koto' },
  { 'family': 'Ethnic', 'instrument': 'Kalimba' },
  { 'family': 'Ethnic', 'instrument': 'Bag pipe' },
  { 'family': 'Ethnic', 'instrument': 'Fiddle' },
  { 'family': 'Ethnic', 'instrument': 'Shanai' },
  { 'family': 'Percussive', 'instrument': 'Tinkle Bell' },
  { 'family': 'Percussive', 'instrument': 'Agogo' },
  { 'family': 'Percussive', 'instrument': 'Steel Drums' },
  { 'family': 'Percussive', 'instrument': 'Woodblock' },
  { 'family': 'Percussive', 'instrument': 'Taiko Drum' },
  { 'family': 'Percussive', 'instrument': 'Melodic Tom' },
  { 'family': 'Percussive', 'instrument': 'Synth Drum' },
  { 'family': 'Percussive', 'instrument': 'Reverse Cymbal' },
  { 'family': 'Sound Effects', 'instrument': 'Guitar Fret Noise' },
  { 'family': 'Sound Effects', 'instrument': 'Breath Noise' },
  { 'family': 'Sound Effects', 'instrument': 'Seashore' },
  { 'family': 'Sound Effects', 'instrument': 'Bird Tweet' },
  { 'family': 'Sound Effects', 'instrument': 'Telephone Ring' },
  { 'family': 'Sound Effects', 'instrument': 'Helicopter' },
  { 'family': 'Sound Effects', 'instrument': 'Applause' },
  { 'family': 'Sound Effects', 'instrument': 'Gunshot' },
]
